services:
  app:
    build: .
    container_name: stayli-app-js
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: stayli-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - stayli-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    container_name: stayli-adminer
    ports:
      - '8080:8080'
volumes:
  stayli-data:
