-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "depositPercentage" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "securityDepositAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "checkInTime" TEXT NOT NULL DEFAULT '14:00',
ADD COLUMN     "checkOutTime" TEXT NOT NULL DEFAULT '10:00';
