import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { Invoice } from '@prisma/client';

@Injectable()
export class InvoicesService {
  constructor(private prisma: PrismaService) {}

  async findAll(): Promise<Invoice[]> {
    return this.prisma.invoice.findMany({ include: { booking: true } });
  }

  async create(data: { dueDate: Date; amount: number; bookingId: string }): Promise<Invoice> {
    // invoiceNumber is generated by DB default; connect booking via relation field
    return this.prisma.invoice.create({
      data: {
        dueDate: data.dueDate,
        amount: data.amount,
        booking: { connect: { id: data.bookingId } },
      },
    });
  }

  // List bookings that do not yet have an invoice (for the create form)
  async findEligibleBookings() {
    return this.prisma.booking.findMany({
      where: { invoice: null },
      include: { property: true, client: true },
    });
  }

  async delete(id: string): Promise<Invoice> {
    return this.prisma.invoice.delete({ where: { id } });
  }

  async findOne(id: string): Promise<Invoice | null> {
    return this.prisma.invoice.findUnique({ where: { id }, include: { booking: true } });
  }

  async update(
    id: string,
    data: {
      invoiceNumber?: string;
      dueDate?: Date;
      amount?: number;
      status?: string;
      bookingId?: string;
    },
  ): Promise<Invoice> {
    const { bookingId, ...rest } = data;
    const updateData: any = { ...rest };
    if (bookingId) {
      updateData.booking = { connect: { id: bookingId } };
      // Avoid passing scalar bookingId when using relation connect
      delete (updateData as any).bookingId;
    }
    return this.prisma.invoice.update({ where: { id }, data: updateData });
  }
}
